### ISSUE TITLE
[FEATURE REQUEST] FX group

### ISSUE THREAD

**Issue by FelipeSCAE** [RxLaboratory/DuGR#42]
Hello I would first like to congratulate you for the nice work with the plugins!
i would like to suggest that we can add fx directly to the created groups, i believe this option would be awesome (this for DUGR)
another option that I really get frustrated with after effects is not being able to manage the layers in an animated way, I mean, it would be amazing if we could animate that a certain layer is above another certain layer, and be able to change the order that which layer would be above which one with keyframes for inversion control, maybe no one will read this.. I don't know, but if anyone reads, there's an idea for a possible new plugin for development by you from rainboxlabs. tnx guys!

**Comment by Nico-Duduf** [comment]
We've given some thoughts to both the features you're suggesting:

1. Add FX to a bunch of layers: you can already do that by using the "select" button in DuGR, then apply the effect of your choice. FX Console by Video Copilot does a pretty good job to help you quickly add effects too.
2. It's not and never will be possible to animate the order of the layers in After Effects, unfortunately. You'll still have to animate opacities or cut the layers... Or use 3D Layers, Note that using the "Calculations" effect on an adjustment layer can help you with that: using it you can bring a layer above others and you just have to animate the effect, instead of cutting/animating opacities.
